CXX ?= gcc

WORK_DIR = $(shell pwd)
BUILD_DIR = $(WORK_DIR)/build

#INC_PATH := $(WORK_DIR)/include $(INC_PATH)

DEBUG ?= 1
ifeq ($(DEBUG), 1) 
	CXXFLAGS += -G
else
	CXXFLAGS += -O2

endif

run: 

clean:

